package edu.charles.tf.entity;

import edu.charles.tf.base.ForeignKeyObject;

import java.util.Date;

public class CustomTokenEntity implements ForeignKeyObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_token.id
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_token.customer_id
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    private CustomerEntity customer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_token.token
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_token.create_time
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_token.update_time
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_token.id
     *
     * @return the value of t_custom_token.id
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_token.id
     *
     * @param id the value for t_custom_token.id
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_token.customer_id
     *
     * @return the value of t_custom_token.customer_id
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public CustomerEntity getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_token.customer_id
     *
     * @param customer the value for t_custom_token.customer_id
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public void setCustomer(CustomerEntity customer) {
        this.customer = customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_token.token
     *
     * @return the value of t_custom_token.token
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_token.token
     *
     * @param token the value for t_custom_token.token
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_token.create_time
     *
     * @return the value of t_custom_token.create_time
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_token.create_time
     *
     * @param createTime the value for t_custom_token.create_time
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_token.update_time
     *
     * @return the value of t_custom_token.update_time
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_token.update_time
     *
     * @param updateTime the value for t_custom_token.update_time
     *
     * @mbg.generated Tue Jan 08 15:34:12 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}