package edu.charles.tf.entity;

import edu.charles.tf.base.ForeignKeyObject;
import edu.charles.tf.domain.SexEnum;
import edu.charles.tf.domain.TypeEnum;
import java.util.Date;

public class CustomerEntity implements ForeignKeyObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.sex
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    private SexEnum sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.age
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.type
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    private TypeEnum type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.description
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.create_time
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.update_time
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.sex
     *
     * @return the value of t_customer.sex
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public SexEnum getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.sex
     *
     * @param sex the value for t_customer.sex
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public void setSex(SexEnum sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.age
     *
     * @return the value of t_customer.age
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.age
     *
     * @param age the value for t_customer.age
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.type
     *
     * @return the value of t_customer.type
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public TypeEnum getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.type
     *
     * @param type the value for t_customer.type
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public void setType(TypeEnum type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.description
     *
     * @return the value of t_customer.description
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.description
     *
     * @param description the value for t_customer.description
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.create_time
     *
     * @return the value of t_customer.create_time
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.create_time
     *
     * @param createTime the value for t_customer.create_time
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.update_time
     *
     * @return the value of t_customer.update_time
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.update_time
     *
     * @param updateTime the value for t_customer.update_time
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}