package edu.charles.tf.entity;

import java.util.Date;

public class TagsEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.desc
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.create_time
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.update_time
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.desc
     *
     * @return the value of tags.desc
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.desc
     *
     * @param desc the value for tags.desc
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.create_time
     *
     * @return the value of tags.create_time
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.create_time
     *
     * @param createTime the value for tags.create_time
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.update_time
     *
     * @return the value of tags.update_time
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.update_time
     *
     * @param updateTime the value for tags.update_time
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}