package edu.charles.tf.entity;

import edu.charles.tf.base.ForeignKeyObject;
import java.util.Date;

public class TagsEntity implements ForeignKeyObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.id
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.name
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.desc
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.create_time
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.update_time
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.id
     *
     * @return the value of t_tags.id
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.id
     *
     * @param id the value for t_tags.id
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.name
     *
     * @return the value of t_tags.name
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.name
     *
     * @param name the value for t_tags.name
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.desc
     *
     * @return the value of t_tags.desc
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.desc
     *
     * @param desc the value for t_tags.desc
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.create_time
     *
     * @return the value of t_tags.create_time
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.create_time
     *
     * @param createTime the value for t_tags.create_time
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.update_time
     *
     * @return the value of t_tags.update_time
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.update_time
     *
     * @param updateTime the value for t_tags.update_time
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}