package edu.charles.tf.mapper.genrator;

import edu.charles.tf.base.mapper.handler.EnumValueTypeHandler;
import edu.charles.tf.entity.CustomerEntity;
import edu.charles.tf.entity.CustomerEntityExample;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CustomerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Tue Jan 08 09:47:11 CST 2019
     */
    @SelectProvider(type=CustomerEntitySqlProvider.class, method="countByExample")
    long countByExample(CustomerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Tue Jan 08 09:47:11 CST 2019
     */
    @DeleteProvider(type=CustomerEntitySqlProvider.class, method="deleteByExample")
    int deleteByExample(CustomerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Tue Jan 08 09:47:11 CST 2019
     */
    @Insert({
        "insert into t_customer (account, name, ",
        "password, sex, ",
        "age, phase, ",
        "type, ",
        "description, create_time, ",
        "update_time)",
        "values (#{account,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{sex,jdbcType=TINYINT,typeHandler=edu.charles.tf.base.mapper.handler.EnumValueTypeHandler}, ",
        "#{age,jdbcType=INTEGER}, #{phase,jdbcType=TINYINT,typeHandler=edu.charles.tf.base.mapper.handler.EnumValueTypeHandler}, ",
        "#{type,jdbcType=TINYINT,typeHandler=edu.charles.tf.base.mapper.handler.EnumValueTypeHandler}, ",
        "#{description,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(CustomerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Tue Jan 08 09:47:11 CST 2019
     */
    @InsertProvider(type=CustomerEntitySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(CustomerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Tue Jan 08 09:47:11 CST 2019
     */
    @SelectProvider(type=CustomerEntitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", typeHandler=EnumValueTypeHandler.class, jdbcType=JdbcType.TINYINT),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="phase", property="phase", typeHandler=EnumValueTypeHandler.class, jdbcType=JdbcType.TINYINT),
        @Result(column="type", property="type", typeHandler=EnumValueTypeHandler.class, jdbcType=JdbcType.TINYINT),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CustomerEntity> selectByExample(CustomerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Tue Jan 08 09:47:11 CST 2019
     */
    @UpdateProvider(type=CustomerEntitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CustomerEntity record,
            @Param("example") CustomerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Tue Jan 08 09:47:11 CST 2019
     */
    @UpdateProvider(type=CustomerEntitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CustomerEntity record, @Param("example") CustomerEntityExample example);
}