package edu.charles.tf.mapper.genrator;

import edu.charles.tf.entity.TagsEntity;
import edu.charles.tf.entity.TagsEntityExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TagsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @SelectProvider(type=TagsEntitySqlProvider.class, method="countByExample")
    long countByExample(TagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @DeleteProvider(type=TagsEntitySqlProvider.class, method="deleteByExample")
    int deleteByExample(TagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Delete({
        "delete from tags",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Insert({
        "insert into tags (name, desc, ",
        "create_time, update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{desc,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(TagsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @InsertProvider(type=TagsEntitySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(TagsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @SelectProvider(type=TagsEntitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TagsEntity> selectByExample(TagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Select({
        "select",
        "id, name, desc, create_time, update_time",
        "from tags",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    TagsEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=TagsEntitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TagsEntity record, @Param("example") TagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=TagsEntitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TagsEntity record, @Param("example") TagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=TagsEntitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TagsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Update({
        "update tags",
        "set name = #{name,jdbcType=VARCHAR},",
          "desc = #{desc,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TagsEntity record);
}