package edu.charles.tf.mapper.genrator;

import edu.charles.tf.base.mapper.handler.ForeignKeyObjectTypeHandler;
import edu.charles.tf.entity.TokenEntity;
import edu.charles.tf.entity.TokenEntityExample;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TokenEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    @SelectProvider(type=TokenEntitySqlProvider.class, method="countByExample")
    long countByExample(TokenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    @DeleteProvider(type=TokenEntitySqlProvider.class, method="deleteByExample")
    int deleteByExample(TokenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    @Insert({
        "insert into t_token (customer_id, ",
        "token, create_time, ",
        "update_time)",
        "values (#{customer,jdbcType=BIGINT,typeHandler=edu.charles.tf.base.mapper.handler.ForeignKeyObjectTypeHandler}, ",
        "#{token,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(TokenEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    @InsertProvider(type=TokenEntitySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(TokenEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    @SelectProvider(type=TokenEntitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT),
        @Result(column="customer_id", property="customer", typeHandler=ForeignKeyObjectTypeHandler.class, jdbcType=JdbcType.BIGINT),
        @Result(column="token", property="token", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TokenEntity> selectByExample(TokenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    @UpdateProvider(type=TokenEntitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TokenEntity record, @Param("example") TokenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Mon Jan 07 18:12:03 CST 2019
     */
    @UpdateProvider(type=TokenEntitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TokenEntity record, @Param("example") TokenEntityExample example);
}