package edu.charles.tengf.mapper.genrator;

import edu.charles.tengf.base.mapper.handler.ForeignKeyObjectTypeHandler;
import edu.charles.tengf.entity.ArticleEntity;
import edu.charles.tengf.entity.ArticleEntityExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ArticleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @SelectProvider(type=ArticleEntitySqlProvider.class, method="countByExample")
    long countByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @DeleteProvider(type=ArticleEntitySqlProvider.class, method="deleteByExample")
    int deleteByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Delete({
        "delete from article",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Insert({
        "insert into article (author_id, ",
        "tag_id, ",
        "title, desc, content, ",
        "create_time, update_time)",
        "values (#{author,jdbcType=BIGINT,typeHandler=edu.charles.tengf.base.mapper.handler.ForeignKeyObjectTypeHandler}, ",
        "#{tags,jdbcType=BIGINT,typeHandler=edu.charles.tengf.base.mapper.handler.ForeignKeyObjectTypeHandler}, ",
        "#{title,jdbcType=VARCHAR}, #{desc,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @InsertProvider(type=ArticleEntitySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @SelectProvider(type=ArticleEntitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="author_id", property="author", typeHandler=ForeignKeyObjectTypeHandler.class, jdbcType=JdbcType.BIGINT),
        @Result(column="tag_id", property="tags", typeHandler=ForeignKeyObjectTypeHandler.class, jdbcType=JdbcType.BIGINT),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ArticleEntity> selectByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Select({
        "select",
        "id, author_id, tag_id, title, desc, content, create_time, update_time",
        "from article",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="author_id", property="author", typeHandler=ForeignKeyObjectTypeHandler.class, jdbcType=JdbcType.BIGINT),
        @Result(column="tag_id", property="tags", typeHandler=ForeignKeyObjectTypeHandler.class, jdbcType=JdbcType.BIGINT),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    ArticleEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=ArticleEntitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ArticleEntity record, @Param("example") ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=ArticleEntitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ArticleEntity record, @Param("example") ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=ArticleEntitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Update({
        "update article",
        "set author_id = #{author,jdbcType=BIGINT,typeHandler=edu.charles.tengf.base.mapper.handler.ForeignKeyObjectTypeHandler},",
          "tag_id = #{tags,jdbcType=BIGINT,typeHandler=edu.charles.tengf.base.mapper.handler.ForeignKeyObjectTypeHandler},",
          "title = #{title,jdbcType=VARCHAR},",
          "desc = #{desc,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ArticleEntity record);
}