package edu.charles.tengf.mapper.genrator;

import edu.charles.tengf.base.mapper.handler.EnumValueTypeHandler;
import edu.charles.tengf.entity.AuthorEntity;
import edu.charles.tengf.entity.AuthorEntityExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AuthorEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @SelectProvider(type=AuthorEntitySqlProvider.class, method="countByExample")
    long countByExample(AuthorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @DeleteProvider(type=AuthorEntitySqlProvider.class, method="deleteByExample")
    int deleteByExample(AuthorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Delete({
        "delete from author",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Insert({
        "insert into author (name, age, ",
        "sex, ",
        "title, description, ",
        "create_time, update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{age,jdbcType=INTEGER}, ",
        "#{sex,jdbcType=CHAR,typeHandler=edu.charles.tengf.base.mapper.handler.EnumValueTypeHandler}, ",
        "#{title,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(AuthorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @InsertProvider(type=AuthorEntitySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(AuthorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @SelectProvider(type=AuthorEntitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="sex", property="sex", typeHandler=EnumValueTypeHandler.class, jdbcType=JdbcType.CHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<AuthorEntity> selectByExample(AuthorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Select({
        "select",
        "id, name, age, sex, title, description, create_time, update_time",
        "from author",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="sex", property="sex", typeHandler=EnumValueTypeHandler.class, jdbcType=JdbcType.CHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    AuthorEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=AuthorEntitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AuthorEntity record, @Param("example") AuthorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=AuthorEntitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AuthorEntity record, @Param("example") AuthorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @UpdateProvider(type=AuthorEntitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AuthorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Sun Dec 30 17:41:30 CST 2018
     */
    @Update({
        "update author",
        "set name = #{name,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER},",
          "sex = #{sex,jdbcType=CHAR,typeHandler=edu.charles.tengf.base.mapper.handler.EnumValueTypeHandler},",
          "title = #{title,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AuthorEntity record);
}