package edu.charles.tf.mapper.genrator;

import edu.charles.tf.base.mapper.handler.ForeignKeyObjectTypeHandler;
import edu.charles.tf.entity.ArticleEntity;
import edu.charles.tf.entity.ArticleEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ArticleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    @SelectProvider(type=ArticleEntitySqlProvider.class, method="countByExample")
    long countByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    @DeleteProvider(type=ArticleEntitySqlProvider.class, method="deleteByExample")
    int deleteByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    @Insert({
        "insert into article (author_id, ",
        "tag_id, ",
        "title, desc, content, ",
        "create_time, update_time)",
        "values (#{author,jdbcType=BIGINT,typeHandler=edu.charles.tf.base.mapper.handler.ForeignKeyObjectTypeHandler}, ",
        "#{tags,jdbcType=BIGINT,typeHandler=edu.charles.tf.base.mapper.handler.ForeignKeyObjectTypeHandler}, ",
        "#{title,jdbcType=VARCHAR}, #{desc,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    @InsertProvider(type=ArticleEntitySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    @SelectProvider(type=ArticleEntitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT),
        @Result(column="author_id", property="author", typeHandler=ForeignKeyObjectTypeHandler.class, jdbcType=JdbcType.BIGINT),
        @Result(column="tag_id", property="tags", typeHandler=ForeignKeyObjectTypeHandler.class, jdbcType=JdbcType.BIGINT),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ArticleEntity> selectByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    @UpdateProvider(type=ArticleEntitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ArticleEntity record, @Param("example") ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Jan 02 16:07:16 CST 2019
     */
    @UpdateProvider(type=ArticleEntitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ArticleEntity record, @Param("example") ArticleEntityExample example);
}