package edu.charles.tf.mapper.genrator;

import edu.charles.tf.base.mapper.handler.ForeignKeyObjectTypeHandler;
import edu.charles.tf.entity.CustomTokenEntity;
import edu.charles.tf.entity.CustomTokenEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CustomTokenEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_custom_token
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    @SelectProvider(type=CustomTokenEntitySqlProvider.class, method="countByExample")
    long countByExample(CustomTokenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_custom_token
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    @DeleteProvider(type=CustomTokenEntitySqlProvider.class, method="deleteByExample")
    int deleteByExample(CustomTokenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_custom_token
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    @Insert({
        "insert into t_custom_token (customer_id, ",
        "token, create_time, ",
        "update_time)",
        "values (#{customer,jdbcType=BIGINT,typeHandler=edu.charles.tf.base.mapper.handler.ForeignKeyObjectTypeHandler}, ",
        "#{token,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(CustomTokenEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_custom_token
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    @InsertProvider(type=CustomTokenEntitySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(CustomTokenEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_custom_token
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    @SelectProvider(type=CustomTokenEntitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT),
        @Result(column="customer_id", property="customer", typeHandler=ForeignKeyObjectTypeHandler.class, jdbcType=JdbcType.BIGINT),
        @Result(column="token", property="token", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CustomTokenEntity> selectByExample(CustomTokenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_custom_token
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    @UpdateProvider(type=CustomTokenEntitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CustomTokenEntity record, @Param("example") CustomTokenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_custom_token
     *
     * @mbg.generated Tue Jan 08 17:54:04 CST 2019
     */
    @UpdateProvider(type=CustomTokenEntitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CustomTokenEntity record, @Param("example") CustomTokenEntityExample example);
}